// Populates apps/web/.env.local from the Convex-provisioned
// packages/backend/.env.local, and generates WORKOS_COOKIE_PASSWORD
// (the one secret Convex does not provision) if it isn't already set.
//
// Values are never printed — only the key names that were written.
// Run with: pnpm sync-web-env

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const backendEnvPath = resolve(root, "packages/backend/.env.local");
const webEnvPath = resolve(root, "apps/web/.env.local");

function parseEnv(text) {
  const out = {};
  for (const line of text.split("\n")) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    if (!m) continue;
    out[m[1]] = m[2].replace(/^["']|["']$/g, "");
  }
  return out;
}

if (!existsSync(backendEnvPath)) {
  console.error("✗ packages/backend/.env.local not found — run `pnpm backend:setup` first.");
  process.exit(1);
}

const backend = parseEnv(readFileSync(backendEnvPath, "utf8"));
const web = existsSync(webEnvPath) ? parseEnv(readFileSync(webEnvPath, "utf8")) : {};

const required = ["CONVEX_URL", "WORKOS_CLIENT_ID", "WORKOS_API_KEY"];
const missing = required.filter((k) => !backend[k]);
if (missing.length) {
  console.error(
    `✗ Missing in packages/backend/.env.local: ${missing.join(", ")}. Re-run \`pnpm backend:setup\`.`,
  );
  process.exit(1);
}

const cookiePreserved = Boolean(web.WORKOS_COOKIE_PASSWORD);
const cookie = web.WORKOS_COOKIE_PASSWORD || randomBytes(32).toString("base64");

const out = {
  NEXT_PUBLIC_CONVEX_URL: backend.CONVEX_URL,
  WORKOS_CLIENT_ID: backend.WORKOS_CLIENT_ID,
  WORKOS_API_KEY: backend.WORKOS_API_KEY,
  WORKOS_COOKIE_PASSWORD: cookie,
  NEXT_PUBLIC_WORKOS_REDIRECT_URI:
    backend.NEXT_PUBLIC_WORKOS_REDIRECT_URI || "http://localhost:3000/callback",
};

const body =
  "# Generated by `pnpm sync-web-env` from packages/backend/.env.local.\n" +
  "# Do not commit. Re-run after re-provisioning Convex/WorkOS.\n" +
  Object.entries(out)
    .map(([k, v]) => `${k}=${v}`)
    .join("\n") +
  "\n";

writeFileSync(webEnvPath, body);

console.log("✓ Wrote apps/web/.env.local with keys:");
for (const k of Object.keys(out)) {
  const note =
    k === "WORKOS_COOKIE_PASSWORD"
      ? cookiePreserved
        ? " (preserved existing)"
        : " (generated)"
      : "";
  console.log(`   - ${k}${note}`);
}
console.log("  (values intentionally not printed)");
